name:                afp
version:             0.1.0.0
github:              "https://github.com/GalLalouche/AdvancedFunctionalProgramming"
license:             MIT
author:              "Gal Lalouche"

dependencies:
- async
- base >= 4.7 && < 5
- boxes
- containers
- directory
- mtl
- QuickCheck
- pretty-tree
- text
- time
- threepenny-gui
- vector

library:
  source-dirs: src

executables:
  afp-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - afp

tests:
  afp-test:
    main:                Driver.hs
    source-dirs:         test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -Wall
      - -Wno-missing-signatures
      - -Wno-name-shadowing
      - -Wno-orphans
      - -Wno-type-defaults
    dependencies:
      - afp
      - HUnit
      - QuickCheck
      - tasty
      - tasty-hunit
      - tasty-hunit-adapter
      - tasty-discover >= 4.2.1
