name:                afp
version:             0.1.0.0
github:              "https://github.com/GalLalouche/AdvancedFunctionalProgramming"
license:             MIT
author:              "Gal Lalouche"

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  afp-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - afp
